resolver: lts-18.27
packages:
  - .

extra-deps:
- hashable-1.3.0.0
- rest-rewrite-0.3.0
- git: https://github.com/ucsd-progsys/liquidhaskell.git
  commit: 4dbafc42400c67b8cd3a7316dbf2c618980c6f44
  subdirs:
    - .
    - liquid-base
    - liquid-containers
    - liquid-ghc-prim
    - liquid-prelude
- git: https://github.com/ucsd-progsys/liquid-fixpoint.git
  commit: b590314a3e7cdabb10d7ad95007963930dfaa6d8
allow-newer: true

nix:
  packages: ["z3"]
