version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD 
    
    steps:
      - run: sudo apt-key del 7fa2af80 && sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/3bf863cc.pub
      - run: apt-get update && apt-get install -y git ssh unzip

      - run: 
          name: Install z3 
          command: |
            wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.15/z3-4.8.15-x64-glibc-2.31.zip
            unzip z3-4.8.15-x64-glibc-2.31.zip
            rm -f z3-4.8.15-x64-glibc-2.31.zip
            cp z3-4.8.15-x64-glibc-2.31/bin/libz3.a /usr/local/lib
            cp z3-4.8.15-x64-glibc-2.31/bin/z3 /usr/local/bin
            cp z3-4.8.15-x64-glibc-2.31/include/* /usr/local/include
            rm -rf z3-4.8.15-x64-glibc-2.31
            z3 --version
      - checkout
      - add_ssh_keys

      - run:
          name: Test Examples 
          command: stack setup && stack build && stack test
