version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD 
    
    steps:
      - run: sudo apt-key del 7fa2af80 && sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/3bf863cc.pub
      - run: apt-get update && apt-get install -y git ssh unzip

      - run: 
          name: Install z3 
          command: |
            wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.15/z3-solver-4.8.15.0.tar.gz
            tar -xvzf z3-solver-4.8.12.0.tar.gz
            cd z3-solver-4.8.15.0 && sudo make install-z3py
            z3 --version
      - checkout
      - add_ssh_keys

      - run:
          name: Test Examples 
          command: stack setup && stack build && stack test
