version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD 
    
    steps:
      - run: sudo apt-key del 7fa2af80 && sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/3bf863cc.pub
      - run: apt-get update && apt-get install -y git ssh unzip
      - checkout
      - add_ssh_keys
            
      - run: 
          name: Install z3 
          command: |
            wget https://github.com/Z3Prover/z3/archive/refs/tags/z3-4.8.15.tar.gz
            tar -xvzf z3-4.8.15.tar.gz
            mkdir z3-z3-4.8.15/build
            cd z3-z3-4.8.15/build && cmake -G "Unix Makefiles" ../
            cd z3-z3-4.8.15/build && make -j4
            ls z3-z3-4.8.15/build
            ln -s z3-z3-4.8.15/build/z3 /usr/bin/z3
            
      
      - run:
          name: Test Examples 
          command: stack setup && stack build && stack test
