name: Haskell CI

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10.3'
        enable-stack: true
        stack-version: 'latest'

    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache
      with:
        path: ~/.stack-work
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('~/stack.yaml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install Z3
      run: |
        wget https://github.com/Z3Prover/z3/releases/download/z3-4.9.1/z3-4.9.1-x64-glibc-2.31.zip
        unzip z3-4.9.1-x64-glibc-2.31.zip
        rm -f z3-4.9.1-x64-glibc-2.31.zip
        cp z3-4.9.1-x64-glibc-2.31/bin/libz3.a /usr/local/lib
        cp z3-4.9.1-x64-glibc-2.31/bin/z3 /usr/local/bin
        cp z3-4.9.1-x64-glibc-2.31/include/* /usr/local/include
        rm -rf z3-4.9.1-x64-glibc-2.31
        z3 --version
    - name: Run tests
      run: stack setup && stack build && stack test
